USE customer_behavior;
-- Q1. What is the total revenue generated by male vs. female customers?


SELECT gender, SUM(purchase_amount) as revenue
from mytable
group by gender



-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM mytable
WHERE discount_applied = 'YES'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM mytable
     );



-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating),2) as "Average product rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5



-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount),2) 
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as average_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from mytable
GROUP by subscription_status 
ORDER by total_revenue and average_spend desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased ,
ROUND(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
FROM mytable
group BY item_purchased
order BY discount_rate desc
limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--     and show the count of each segment.

WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'NEW'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
            ELSE 'LOYAL'
        END AS customer_segment
    FROM mytable
)

SELECT 
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status




-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;







